### ISSUE TITLE
---> 17 from transformers import BeamSearchScorer, LogitsProcessorList, MinLengthLogitsProcessor, StoppingCriteriaList, MaxLengthCriteria

### ISSUE THREAD

**Issue by xirtus** [alembics/disco-diffusion#174]
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-6-3c8357fba9cb>](https://localhost:8080/#) in <module>
     46 try:
---> 47     import open_clip
     48 except:

6 frames
ModuleNotFoundError: No module named 'transformers'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
[/content/open_clip/src/open_clip/coca_model.py](https://localhost:8080/#) in <module>
     15 from .model import CLIPTextCfg, CLIPVisionCfg, _build_vision_tower, _build_text_tower
     16 from .generation_utils import top_a, top_k, top_p, prepare_inputs_for_generation
---> 17 from transformers import BeamSearchScorer, LogitsProcessorList, MinLengthLogitsProcessor, StoppingCriteriaList, MaxLengthCriteria
     18 
     19 GENERATION_TYPES = {

ModuleNotFoundError: No module named 'transformers'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by mlalves13** [comment]
mine is doing the same

**Comment by Naed9** [comment]
Also having this issue. Someone on reddit suggested running "!pip install -qq open_clip_torch" but that did not work for me, and I don't understand python well enough to troubleshoot.

**Comment by Naed9** [comment]
v5.61 started working for me today without any changes.

**Comment by aletts** [comment]
I just tried the latest notebook ( at discodiffusion.com ) and it's working fine for me.
I'm hoping the issue was due to some external problem which has since been fixed.. but if you're still experiencing any issues, please describe any more details such as: Are you running it on Colab (vs local)? Which version of the notebook are you running?

As an aside, I just noticed now that notebook includes the versions v5.61 and v5.7 since I probably failed to update a string somewhere. When this does happen, I'd suggest mentioning the latest version seen.
