### ISSUE TITLE
Does the mac work? Is the GPU that the M1 processor carries okay?

### ISSUE THREAD

**Issue by 252552899** [alembics/disco-diffusion#84]
Does the mac work? Is the GPU that the M1 processor carries okay?

**Comment by aletts** [comment]
Currently, it wouldn't use the M1's GPU. So in order for it to work locally (rather than on Colab as most people do) on a Mac at all, you'd have to limit it to using the CPU by checking `useCPU`.

There was recently an announcement from PyTorch that the next version of PyTorch will support the M1's GPU. So we'll see what happens when that comes. Until now, Nvidia's CUDA is basically what everyone uses for GPU acceleration.
